version: "3.9"
services:
  api:
    build: .
    ports: ["5000:5000"]
    environment:
      - MODEL_PATH=/app/models/exoplanet_clf.joblib
      - DB_PATH=/app/exoplanetes.db
    volumes:
      - exodb:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/healthz"]
      interval: 30s
      timeout: 3s
      retries: 3
volumes:
  exodb:
